Feature/game anti cheat v1
xebia-france/who-is-2-turbo-services pull request #9
Opened 2021-07-05 15:20 UTC by rgeorges-psf

2021-07-05 15:28 UTC, blacroix commented on functions/.runtimeconfig.json
> +    "baseurl": "http://localhost:5001/who-is-2-turbo/europe-west1/api",
Ce fichier est-il nécessaire ?

2021-07-05 15:28 UTC, blacroix commented on functions/src/infrastructure/crypto/Crypto.service.ts
> +  cypher(data: string): string {
Ce code a été copié de quelque part (et donc citer la source) ?

2021-07-05 15:38 UTC, rgeorges-psf commented on functions/.runtimeconfig.json
> +    "baseurl": "http://localhost:5001/who-is-2-turbo/europe-west1/api",
oui il permet de setter les variables d'environnement sur le simulateur local (voir readme pour le deploy sur firebase)

2021-07-05 15:48 UTC, rgeorges-psf commented on functions/src/infrastructure/crypto/Crypto.service.ts
> +  cypher(data: string): string {
?
c'est juste un appel de l'API crypto de nodejs, tu veux citer quoi ? la doc de nodejs ?

2021-07-05 16:28 UTC, blacroix commented on functions/src/infrastructure/crypto/Crypto.service.ts
> +  cypher(data: string): string {
Nous pourrions ajouter un timestamp pour faire en sorte que l'image soit disponible qu'un temps limité ? Je suggestionne 60 min ;)

2021-07-12 15:20 UTC, rgeorges-psf commented on functions/src/infrastructure/crypto/Crypto.service.ts
> +  cypher(data: string): string {
fait

2021-07-22 08:04 UTC, cdreyfus requested changes

2021-07-22 08:04 UTC, cdreyfus commented on functions/src/application/game/game.controller.ts
> +    res.setHeader('Content-Type', 'image/webp');
tu peux récupérer le type depuis l'image, il est dans le mimetype du ficher

2021-07-22 08:04 UTC, cdreyfus commented on functions/src/application/game/game.controller.ts
> +    res.setHeader('Content-Type', 'image/webp');
le webp est probable mais pas toujours certain

2021-12-22 20:58 UTC, closed without merging